# Generated by Django 3.0.3 on 2020-02-16 01:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ass_type', models.CharField(max_length=30)),
                ('grade_percentage', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.course')),
            ],
        ),
        migrations.DeleteModel(
            name='assTypes',
        ),
        migrations.AddField(
            model_name='assignment',
            name='ass_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grades.assType'),
            preserve_default=False,
        ),
    ]
