# Generated by Django 3.0.2 on 2020-02-16 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 15, 20, 5, 4, 29631)),
        ),
    ]
