# Generated by Django 3.0.2 on 2020-03-05 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20200221_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
