# Generated by Django 3.0.2 on 2020-03-05 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_course_course_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
