# Generated by Django 3.0.2 on 2020-03-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_auto_20200306_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='improved',
            field=models.BooleanField(blank=True, default=None),
        ),
    ]
