# Generated by Django 3.0.2 on 2020-03-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_auto_20200306_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='improved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
