# Generated by Django 3.0.2 on 2020-03-07 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0008_assignment_ass_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='ass_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='grades.assType'),
        ),
    ]
