# Generated by Django 3.0.2 on 2020-03-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0012_course_pointbased'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='pointbased',
            field=models.BooleanField(default=False),
        ),
    ]
