# Generated by Django 3.0.2 on 2020-03-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0014_remove_assignment_pointbased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pointbased',
            field=models.BooleanField(default=True),
        ),
    ]
