# Generated by Django 3.0.2 on 2020-03-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0015_auto_20200326_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pointbased',
            field=models.BooleanField(default=False),
        ),
    ]
