# Generated by Django 3.0.2 on 2020-03-27 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0017_pointassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_grade_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='course',
            name='point_improved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
