# Generated by Django 3.0.2 on 2020-03-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0016_auto_20200327_1844'),
        ('grades', '0018_auto_20200326_2008'),
    ]

    operations = [
    ]
