# Generated by Django 3.0.2 on 2020-04-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0019_merge_20200329_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='earned_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
