# Generated by Django 3.0.5 on 2020-04-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0020_auto_20200418_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointassignment',
            name='points_total',
            field=models.IntegerField(default=1),
        ),
    ]
