# Generated by Django 3.0.2 on 2020-02-16 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 15, 19, 7, 41, 306113)),
        ),
    ]
