# Generated by Django 3.0.2 on 2020-03-01 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200229_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 29, 23, 59, 14, 735527)),
        ),
    ]
