# Generated by Django 3.0.2 on 2020-03-26 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_auto_20200325_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 26, 10, 36, 0, 944792)),
        ),
    ]
