# Generated by Django 3.0.2 on 2020-03-26 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_auto_20200326_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 26, 11, 5, 29, 978762)),
        ),
    ]
