# Generated by Django 3.0.2 on 2020-03-26 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0024_auto_20200326_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 26, 12, 39, 33, 22030)),
        ),
    ]
