# Generated by Django 3.0.2 on 2020-03-26 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_auto_20200326_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 26, 13, 54, 34, 81418)),
        ),
    ]
