# Generated by Django 3.0.4 on 2020-03-23 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0027_auto_20200322_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 23, 27, 31, 981479)),
        ),
    ]
