# Generated by Django 3.0.4 on 2020-03-23 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0031_auto_20200323_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 17, 48, 52, 93245)),
        ),
    ]
