# Generated by Django 3.0.4 on 2020-03-25 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0032_auto_20200323_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 25, 16, 12, 36, 312763)),
        ),
    ]
