# Generated by Django 3.0.4 on 2020-03-27 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0035_auto_20200327_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 27, 18, 44, 17, 441798)),
        ),
    ]
