# Generated by Django 3.0.2 on 2020-03-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0028_auto_20200326_2008'),
        ('todo', '0037_auto_20200328_1724'),
    ]

    operations = [
    ]
