# Generated by Django 3.0.2 on 2020-04-06 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0038_merge_20200329_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 18, 4, 59, 667896)),
        ),
    ]
