# Generated by Django 3.0.2 on 2020-04-08 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0040_auto_20200406_1917'),
        ('todo', '0039_auto_20200407_1758'),
    ]

    operations = [
    ]
