# Generated by Django 3.0.3 on 2020-04-08 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0041_merge_20200407_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='owner',
        ),
        migrations.AddField(
            model_name='todo',
            name='group',
            field=models.CharField(default='school', max_length=60),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 14, 22, 0, 510234)),
        ),
    ]
