# Generated by Django 3.0.3 on 2020-04-08 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0042_auto_20200408_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 14, 32, 35, 545640)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='group',
            field=models.CharField(default='school', max_length=100),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
