# Generated by Django 3.0.2 on 2020-04-08 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0045_todo_owner'),
        ('todo', '0044_auto_20200408_2100'),
    ]

    operations = [
    ]
