# Generated by Django 3.0.2 on 2020-04-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarMod', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='month_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
