# Generated by Django 3.0.2 on 2020-04-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarMod', '0003_event_month_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='from_google',
            field=models.BooleanField(default=False),
        ),
    ]
