# Generated by Django 3.0.2 on 2020-04-08 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarMod', '0006_auto_20200408_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='month_name',
            new_name='start_month_name',
        ),
    ]
