# Generated by Django 3.0.2 on 2020-04-08 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarMod', '0007_auto_20200408_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
