# Generated by Django 3.0.2 on 2020-04-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarMod', '0009_event_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_month_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='endhour',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='starthour',
            field=models.TextField(default=''),
        ),
    ]
